from kivymd.uix.behaviors.touch_behavior import TouchBehavior as TouchEffect
from kivymd.uix.behaviors.ripple_behavior import CircularRippleBehavior as CircularRippleEffect
from kivymd.uix.behaviors.ripple_behavior import RectangularRippleBehavior as RectangularRippleEffect
